-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Jeu 27 Avril 2017 à 23:45
-- Version du serveur :  10.1.19-MariaDB
-- Version de PHP :  5.6.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `dev_web`
--

-- --------------------------------------------------------

--
-- Structure de la table `interventions`
--

CREATE TABLE `interventions` (
  `id_intervention` int(9) NOT NULL,
  `id_cat_inter` int(5) NOT NULL,
  `nom` varchar(50) NOT NULL,
  `slug` varchar(25) NOT NULL,
  `definition` text NOT NULL,
  `utilite` text NOT NULL,
  `titre` varchar(250) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Contenu de la table `interventions`
--

INSERT INTO `interventions` (`id_intervention`, `id_cat_inter`, `nom`, `slug`, `definition`, `utilite`, `titre`) VALUES
(1, 1, 'HTML', 'html', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex eveniet sunt, at voluptatem ducimus. Ea, eveniet reiciendis rem maxime natus blanditiis! Accusantium doloribus dolores accusamus. Beatae repudiandae rem aut expedita ex aspernatur labore necessitatibus, ut at est doloremque ratione harum id consequatur error, voluptatum facilis veniam voluptatem a cupiditate, quidem. Repellat nemo nulla minus. Officiis sint dignissimos corporis tempora harum quia, nesciunt deleniti facilis dolor molestias porro est dolore obcaecati ullam non rem libero, nam consectetur qui nostrum assumenda pariatur perspiciatis. Ad soluta, dolores ipsum voluptas. Iusto natus nulla sint architecto, neque, possimus non culpa ad exercitationem, reprehenderit dolores. Deserunt ipsum saepe voluptate dignissimos, excepturi aperiam. Quasi in maxime eaque tempora aperiam consectetur unde nesciunt, dolores quam corporis temporibus iusto maiores deleniti sed alias incidunt sunt repellendus error repellat fugit ducimus at quas esse culpa quaerat! Temporibus harum iusto maiores ipsa expedita quis delectus! Aliquid laboriosam labore numquam dicta tenetur?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis dolorem rerum dicta neque laudantium exercitationem commodi ipsum quas, facilis alias odit, minima aliquid soluta. Iure unde iusto vitae repellendus, veritatis eaque consectetur, explicabo quibusdam nesciunt vel. Iste saepe, reprehenderit distinctio cum molestias odio perspiciatis quasi unde tempora quod esse quisquam.', 'HTML (HyperText Markup Language).'),
(2, 1, 'CSS', 'css', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, cumque quo voluptate modi quibusdam atque debitis dolore animi tenetur tempora ipsa beatae iusto placeat reiciendis voluptates. Vitae reiciendis officia a, quisquam ad, nobis voluptatibus illo fuga sint similique tenetur quo asperiores, saepe impedit exercitationem consectetur autem. Enim voluptatibus sapiente officiis ad ratione, aut architecto nemo soluta quas, facere dolores esse blanditiis eius reprehenderit eaque? Illo praesentium nihil culpa soluta assumenda minus doloribus quo odit consequuntur officia reprehenderit aspernatur voluptatem laboriosam, delectus quasi repellat voluptatum temporibus nostrum, mollitia iure, dolore ad in error hic placeat! Architecto enim sint eligendi ut pariatur minus quas numquam nihil autem modi voluptatum nobis sed, ab! Eum maxime neque voluptates ut tenetur perspiciatis esse tempore maiores distinctio placeat assumenda numquam itaque porro ratione deserunt aperiam blanditiis accusamus corporis, consectetur nemo veniam odio doloribus? Ipsam, ex, illo nam delectus perspiciatis hic? Modi alias minus debitis porro, officia.&lt;/p&gt;', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae possimus repellat, nemo deserunt voluptatum commodi ab asperiores rem, laboriosam qui veniam corrupti aut, ullam nesciunt! Assumenda asperiores magnam, exercitationem alias facilis iusto porro fugiat debitis sed, excepturi eum ullam sunt voluptatem ab? Sapiente unde repellendus, sunt repudiandae nobis ab voluptatem.&lt;/p&gt;', 'Qu''est-ce que CSS ?'),
(3, 1, 'JavaScript', 'javascript', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora aspernatur voluptatum facere, totam eaque, repellat aliquam debitis maiores molestiae quo, velit in laboriosam! Eveniet est necessitatibus reprehenderit voluptates, pariatur rerum nesciunt quo ab laudantium vel eaque animi hic non aperiam veniam, quae unde recusandae accusamus aliquid, nisi natus rem possimus! Quaerat, atque! Doloremque maiores minima ea, in excepturi voluptate eligendi non aperiam molestias, est, explicabo similique vel illo nisi? Maiores harum ullam hic natus architecto, est velit nobis sed quod in esse dolorem eligendi maxime blanditiis saepe iure perspiciatis quas fuga quaerat quisquam. Similique facilis, veniam repudiandae velit hic! Consequuntur quam libero ab, ut ipsa deserunt. Eligendi vel quas, aperiam praesentium, architecto in asperiores voluptatem vitae rerum at aut quae facere, rem necessitatibus, blanditiis odio velit autem. Quam ut odio blanditiis ad neque quaerat, maxime animi sit necessitatibus quisquam impedit amet, ab eum eos cumque perspiciatis voluptatibus pariatur quidem facilis.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque similique, commodi excepturi, iusto provident unde enim cupiditate. Quam impedit architecto alias, iste numquam adipisci illum id temporibus quasi expedita omnis, dignissimos veritatis recusandae, explicabo voluptatibus itaque illo totam autem animi? Harum natus cumque totam, voluptatibus dolores mollitia maxime aut recusandae.', 'Qu''est-ce que Javascript ?'),
(4, 2, 'D&eacute;veloppement', 'developpement', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt modi eaque laborum similique voluptatem. Dignissimos fuga quisquam soluta ex, ipsum libero optio fugiat aspernatur nulla perferendis cumque eos quod eligendi quo blanditiis repellat molestiae quam quos nobis deleniti ea quaerat distinctio, laudantium atque quia? Id ea quos aperiam, vel eaque dignissimos, ipsa cumque voluptatum, asperiores nostrum voluptatibus. Expedita officiis et totam qui sed, consectetur autem unde quis nesciunt eum minus tempora mollitia. Dolore nihil cumque magnam vel id dolorum? Libero reiciendis ullam voluptas facilis quos, aut in, placeat laborum iste cumque perspiciatis? Voluptate sequi soluta qui, optio. Ipsum, illo. Officia eligendi aliquid cumque sed, quos possimus blanditiis non debitis placeat, veritatis repellat totam. Est labore corporis voluptates dolore repudiandae officiis quas fugit, quaerat earum porro illo laborum necessitatibus, neque magni! Facere et, odit velit nam, quo voluptate quos veniam architecto omnis ex iste. Architecto dolor itaque aperiam illo. Temporibus, iste!', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam eaque praesentium soluta incidunt, animi quam porro deleniti, optio. Saepe repudiandae deserunt veniam itaque, ullam ipsa amet assumenda accusantium doloremque numquam quaerat qui nobis animi molestias placeat ea rerum ducimus ipsum minima delectus quisquam fugit eaque excepturi. Cumque, quia optio dolorum!', 'Le d&eacute;veloppement d''une application web.'),
(5, 1, 'Int&eacute;gration', 'integration', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem architecto delectus id similique odit dignissimos modi sunt accusantium, aliquam nisi fugiat nostrum voluptatibus. Eligendi tenetur porro doloremque consectetur officiis earum ducimus excepturi, voluptate atque, sed obcaecati delectus, pariatur minus aspernatur accusamus consequatur tempore omnis id iste ipsum sequi distinctio repellat ex saepe! Reprehenderit repudiandae ipsum a commodi, ut atque id, accusantium, maiores, nemo quae praesentium ad vitae? Totam dolorum corporis, incidunt necessitatibus praesentium quam ipsam eum tenetur eveniet! Atque, eius, eaque. Dolor alias fuga adipisci ab velit assumenda cupiditate? Recusandae itaque voluptas dolorem esse cupiditate veritatis, asperiores, commodi culpa magni expedita assumenda fugit possimus inventore odio cumque voluptates iusto enim rem maiores? Beatae enim, provident et, reiciendis eveniet, eius praesentium delectus at inventore distinctio id non officia maxime, mollitia asperiores rem repellendus itaque pariatur! Labore exercitationem enim, ex dolorum, officiis ratione ipsa molestiae vitae porro, velit beatae, officia odit alias!', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione iusto vitae, maiores atque fugit ea delectus quia doloribus error magnam inventore aliquid neque nisi mollitia laboriosam culpa totam voluptatum ducimus. Pariatur tempora modi assumenda laborum natus hic magni blanditiis facilis repudiandae corporis aliquam, cumque deleniti ad nesciunt incidunt quos explicabo.', 'Int&eacute;gration valid&eacute; W3C'),
(6, 3, 'Web Design', 'web-design', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam, molestias atque consequuntur dolor ratione dolore, eum. Iusto quibusdam unde porro blanditiis voluptates, a laboriosam rem omnis optio dolor alias consequuntur, vel odio praesentium quaerat dolorum veritatis rerum reprehenderit repellat architecto earum, quidem dolorem voluptate. At qui deserunt, hic tenetur ex cum nobis repudiandae, cumque beatae culpa itaque est aut facilis vitae autem expedita quia eum nisi a illo cupiditate repellendus nam! Odio, enim! Ipsum alias temporibus possimus fugiat magni amet unde, nam ut labore deleniti quibusdam impedit porro facere, repellendus quos. Officia est voluptas alias explicabo ducimus quod tempora, dolores ullam in tempore. Illo reprehenderit non sapiente, repellendus ducimus, recusandae! Magni sunt et, animi sed qui facilis explicabo? Animi architecto maxime nobis temporibus, odio consequatur ullam quisquam at est soluta molestias, optio officia incidunt, porro quo non alias, repellat inventore aspernatur provident commodi! Quas nisi, rerum eius iste vero iure.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod vitae qui, dolore numquam dolorum iusto. Mollitia, dolores possimus quis autem quaerat nostrum vitae vel repudiandae a corporis quidem nihil molestiae, quas adipisci neque est reiciendis ipsam. Voluptatum mollitia ad eum, maxime assumenda, non! Architecto voluptas tempore mollitia nesciunt necessitatibus adipisci.', 'Webdesign et maquette fonctionnelle'),
(7, 2, 'PHP', 'php', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil blanditiis maiores sequi molestiae expedita dignissimos veniam ducimus deserunt suscipit quaerat, sint asperiores. Delectus totam tempora, neque molestias soluta fugiat explicabo, provident rem sed, cum eos nisi ipsum sequi aspernatur error voluptatem. Quis asperiores dolorem inventore voluptatibus, recusandae ad et praesentium. Totam, quo, molestias. Reprehenderit corrupti veritatis laudantium ipsum repudiandae tenetur fugiat rerum, illum omnis perspiciatis ut error magnam, dignissimos animi debitis? Fuga iste ea autem in error aliquam dignissimos recusandae ab, ad architecto voluptas doloribus, suscipit deserunt expedita laboriosam unde velit fugit earum nisi quod aut repellat inventore atque. Quisquam expedita sapiente harum suscipit eum sunt sint error, necessitatibus ducimus! Explicabo tempore laudantium dolores architecto temporibus, eligendi nisi consectetur praesentium quaerat impedit magnam minima voluptas voluptate porro magni inventore quae, ipsam neque est. Iusto fuga sit eligendi, eos neque est, asperiores quae laboriosam commodi repellat, dolorum amet consequatur vitae labore.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, iste! Veniam praesentium neque, inventore magnam illo amet, repudiandae ab exercitationem harum laboriosam eaque consectetur aperiam nobis earum hic numquam ad similique vitae et! Modi vel tempora aliquid, fuga et iure, odit officia explicabo accusantium cumque saepe provident eligendi nulla nihil.', 'PHP (Hypertext Preprocessor)'),
(8, 2, 'MySql', 'mysql', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat consectetur odit saepe, deserunt suscipit reprehenderit voluptas, accusamus, repudiandae corporis perspiciatis similique quidem vel dolor soluta necessitatibus quasi aperiam nam optio fugit ullam doloribus ut molestias repellat libero. Quibusdam alias quis, voluptas exercitationem dolorem, deleniti expedita corporis, molestiae consectetur voluptatibus aliquid. Ex nemo molestias obcaecati vero, ullam sequi dolorem, facere voluptatum libero quos culpa. Placeat vero soluta, recusandae voluptates aliquid quibusdam odit minus consectetur saepe harum quas explicabo officiis facilis molestias cumque eius dicta quidem eligendi, alias ab numquam omnis quae reiciendis, consequuntur! Hic ipsam, eos expedita magnam consectetur placeat optio voluptate modi maxime, commodi, consequuntur reprehenderit dolores! Sequi in debitis minima, labore optio tenetur odit. Nisi magnam vero enim corporis obcaecati doloremque laboriosam id facilis aut itaque possimus commodi ad, sint eum dolorem soluta assumenda dolores, maxime! Eum corporis quos ducimus, nulla provident numquam, nihil minima iste consequuntur molestiae ad.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa quos laboriosam excepturi nulla, placeat tempore dolores sunt necessitatibus fugit ea itaque ipsum repudiandae fugiat eligendi magnam quisquam non tempora labore harum, cumque odit maiores in voluptates obcaecati? Enim, vero, consectetur, assumenda blanditiis veritatis dolore ipsum qui amet accusamus incidunt accusantium.', 'Qu''est-ce que Sql (Structured Query Language) ?'),
(9, 1, 'W3C', 'w3c', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, recusandae tempora soluta placeat ipsam doloremque? Nihil ut assumenda reprehenderit dolore beatae eveniet numquam dolor, ab quibusdam laudantium fuga enim animi at reiciendis alias, inventore esse velit nemo accusamus vero voluptatem, facilis a? Quaerat ullam magnam voluptas labore dolores nihil saepe dolorem, quod alias itaque assumenda placeat aperiam, rem explicabo, maxime iusto, incidunt sapiente blanditiis! Voluptas, rerum, vero. Unde tempora soluta ducimus laudantium asperiores corporis, explicabo numquam, nisi pariatur fuga! Molestiae in cumque possimus vero harum voluptatum error rem ducimus? Qui odit, fuga est nesciunt iure aperiam labore dolor. Ipsum, cupiditate quae ipsa officiis tempora, animi eligendi, a blanditiis illo obcaecati ratione repellendus repellat quas voluptatum minima. Voluptate sint voluptatum, labore voluptatibus animi sit quo ipsa sequi culpa laborum fuga, illo? Neque cupiditate fugiat, aperiam earum accusantium minus expedita officiis incidunt unde eum perspiciatis inventore nemo, quisquam adipisci enim laudantium sunt.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet quia eos doloribus voluptatum doloremque inventore numquam sunt sit officia non iure fugiat magnam, pariatur ratione eius eaque. Saepe totam perspiciatis velit, labore adipisci fugiat, voluptatem sunt distinctio deleniti est similique libero. Laborum, libero. Libero iste quasi, a consectetur perferendis, magni.', 'Le code source HTML valid&eacute; par les normes W3C');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `interventions`
--
ALTER TABLE `interventions`
  ADD PRIMARY KEY (`id_intervention`),
  ADD KEY `id_cat_inter` (`id_cat_inter`) USING BTREE;

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `interventions`
--
ALTER TABLE `interventions`
  MODIFY `id_intervention` int(9) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
